// <auto-generated />
using System;
using Banco.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banco.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(ContextoDoBanco))]
    [Migration("20260922174904_RevisaoEPagamento")]
    partial class RevisaoEPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SequenciaDeContas");

            modelBuilder.Entity("Banco.Dominio.Contas.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AbertaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SequenciaDeEstado")
                        .HasColumnType("bigint");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("UltimaSequencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Contas_Numero");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Contas.MudancaDeEstadoDaConta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("De")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OcorridaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Para")
                        .HasColumnType("int");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "Sequencia")
                        .IsUnique()
                        .HasDatabaseName("IX_MudancasDeEstadoDaConta_ContaId_Sequencia");

                    b.ToTable("MudancasDeEstadoDaConta", (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Documentos.CampoDoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confianca")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTimeOffset?>("CorrigidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrigidoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<string>("ValorCorrigido")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ValorLido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_CamposDoDocumento_DocumentoId_Nome");

                    b.ToTable("CamposDoDocumento", (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("Confianca")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("ConfiancaDoTexto")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConteudoExtraido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExtraidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("LancamentoDoPagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LeaseAte")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("TamanhoEmBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoDoPagamentoId")
                        .HasDatabaseName("IX_Documentos_LancamentoDoPagamentoId");

                    b.HasIndex("ContaId", "Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Documentos_ContaId_Hash");

                    b.HasIndex("Estado", "LeaseAte")
                        .HasDatabaseName("IX_Documentos_Estado_LeaseAte");

                    b.HasIndex("Estado", "RecebidoEm")
                        .HasDatabaseName("IX_Documentos_Estado_RecebidoEm");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Ledger.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SaldoDepois")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransferenciaId")
                        .HasDatabaseName("IX_Lancamentos_TransferenciaId")
                        .HasFilter("[TransferenciaId] IS NOT NULL");

                    b.HasIndex("ContaId", "ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Lancamentos_ContaId_ChaveIdempotencia");

                    b.HasIndex("ContaId", "Sequencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Lancamentos_ContaId_Sequencia");

                    b.HasIndex("ContaId", "CriadoEm", "Sequencia")
                        .HasDatabaseName("IX_Lancamentos_ContaId_CriadoEm_Sequencia");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Transferencias.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ContaDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId")
                        .HasDatabaseName("IX_Transferencias_ContaDestinoId");

                    b.HasIndex("ContaOrigemId", "ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Transferencias_ContaOrigemId_ChaveIdempotencia");

                    b.ToTable("Transferencias", (string)null);
                });

            modelBuilder.Entity("Banco.Infraestrutura.Persistencia.LinhaDaConciliacao", b =>
                {
                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Lancamentos")
                        .HasColumnType("bigint");

                    b.Property<long>("MaiorSequenciaNoLedger")
                        .HasColumnType("bigint");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("QuebrasNaCorrente")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SaldoMaterializado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SomaDoLedger")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UltimaSequenciaDaConta")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Contas.MudancaDeEstadoDaConta", b =>
                {
                    b.HasOne("Banco.Dominio.Contas.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Banco.Dominio.Documentos.CampoDoDocumento", b =>
                {
                    b.HasOne("Banco.Dominio.Documentos.Documento", null)
                        .WithMany("Campos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banco.Dominio.Documentos.Documento", b =>
                {
                    b.HasOne("Banco.Dominio.Contas.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Banco.Dominio.Ledger.Lancamento", b =>
                {
                    b.HasOne("Banco.Dominio.Contas.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Banco.Dominio.Transferencias.Transferencia", b =>
                {
                    b.HasOne("Banco.Dominio.Contas.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banco.Dominio.Contas.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Banco.Dominio.Documentos.Documento", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
