// <auto-generated />
using System;
using Banco.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banco.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(ContextoDoBanco))]
    [Migration("20260907164946_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SequenciaDeContas");

            modelBuilder.Entity("Banco.Dominio.Contas.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AbertaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("UltimaSequencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Contas_Numero");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Ledger.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SaldoDepois")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Lancamentos_ContaId_ChaveIdempotencia");

                    b.HasIndex("ContaId", "CriadoEm")
                        .HasDatabaseName("IX_Lancamentos_ContaId_CriadoEm");

                    b.HasIndex("ContaId", "Sequencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Lancamentos_ContaId_Sequencia");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("Banco.Infraestrutura.Persistencia.LinhaDaConciliacao", b =>
                {
                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Lancamentos")
                        .HasColumnType("bigint");

                    b.Property<long>("MaiorSequenciaNoLedger")
                        .HasColumnType("bigint");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("QuebrasNaCorrente")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SaldoMaterializado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SomaDoLedger")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UltimaSequenciaDaConta")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Banco.Dominio.Ledger.Lancamento", b =>
                {
                    b.HasOne("Banco.Dominio.Contas.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
